apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: dj-git-indexer
spec:
  image: ghcr.io/vino9org/dj-git-indexer
  interval: 1m0s
  secretRef:
    name: ghcr-cred

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: git-indexer-tag
spec:
  imageRepositoryRef:
    name: dj-git-indexer
  filterTags:
    pattern: '(?P<tag>^v-\d.*)'
    extract: '$tag'
  policy:
    alphabetical:
      order: asc
