apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: core-sim
spec:
  image: ghcr.io/vino9org/core_sim
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: core-sim
spec:
  imageRepositoryRef:
    name: core-sim
  filterTags:
    pattern: '^develop-(?P<suffix>\d{8}\-\d{6}-[0-9a-f]{7})'
    extract: '$suffix'
  policy:
    alphabetical:
      order: asc

