apiVersion: batch/v1
kind: CronJob
metadata:
  name: git-indexer
spec:
  suspend: true
  schedule: "0 * * * *"
  jobTemplate:spec:
  selector:
    matchLabels:
      app: git-indexer
  replicas: 1
  template:
    metadata:
      labels:
        app: git-indexer
    spec:
      containers:
      - name: git-indexer
        image: ghcr.io/sloppycoder/git-commit-indexer:develop-20230622-194026-5d9c264 # {"$imagepolicy": "bbx-dev:git-indexer-develop"}
        imagePullSecrets:
        - name: ghcr-cred
        env:
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: bbx-dev-secret
              key: gitlab-token
        volumeMounts:
        - name: data
          mountPath: /data
      restartPolicy: OnFailure
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: git-indexer-data
