apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-indexer-web
spec:
  selector:
    matchLabels:
      app: git-indexer-web
  replicas: 1
  template:
    metadata:
      labels:
        app: git-indexer-web
    spec:
      containers:
      - name: git-indexer
        image: ghcr.io/sloppycoder/git-commit-indexer:develop-20230704-211141-124c322 # {"$imagepolicy": "bbx-dev:git-indexer-develop"}
        # command: ["bin/sleep", "10000"]
        command: ["gunicorn", "-w", "1", "gui:app", "--bind", "0.0.0.0:8000"]
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: sqlite:////data/git-indexer/git-indexer.db
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: git-indexer-data
---
apiVersion: v1
kind: Service
metadata:
  name: git-indexer-web
spec:
  type: ClusterIP
  selector:
    app: git-indexer-web
  ports:
  - name: http
    port: 8000
