apiVersion: batch/v1
kind: CronJob
metadata:
  name: git-indexer
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: git-indexer
        spec:
          containers:
          - name: git-indexer
            image: ghcr.io/sloppycoder/git-commit-indexer:develop-20230622-194026-5d9c264 # {"$imagepolicy": "bbx-dev:git-indexer-develop"}
            env:
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bbx-dev-secret
                  key: gitlab-token
            volumeMounts:
            - name: data
              mountPath: /data
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
          - name: ghcr-cred
          restartPolicy: OnFailure
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: git-indexer-data
