apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
spec:
  replicas: 1
  image: postgres:13.1
  port: 5432
  database:
    size: 500Mi
  customConfig: postgres-init-scripts
  env:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: git-indexer-secret
        key: postgres-password
  - name: POSTGRES_REPLICATION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: git-indexer-secret
        key: postgres-replication-password
  - name: APP_PGUSER
    value: git
  - name: APP_PGPASSWORD
    value: git
