apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: git-indexer-postgres
spec:
  replicas: 1
  image: postgres:14.5
  database:
    size: 3Gi
  env:
  # skip all the security here :))
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: postgres_password
  - name: POSTGRES_REPLICATION_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: postgres_replication_password
