apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-banking-sim
spec:
  selector:
    matchLabels:
      app: core-banking-sim
  replicas: 1
  template:
    metadata:
      labels:
        app: core-banking-sim
    spec:
      containers:
      - name: core-banking-sim
        image: ghcr.io/vino9org/core-banking-sim:develop-20230603-194136-0cfbd14 # {"$imagepolicy": "vinobank-dev:core-banking-sim-develop"}
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_OM_URL
          value: redis://redis:6379/0
        - name: EVENT_SINK_TYPE
          value: NONE
        - name: BYPASS
          value: "0"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credential
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credential
              key: aws_secret_access_key
        - name: NEW_RELIC_APP_NAME
          value: core-banking-sim
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license-key
              namespace: infra
              key: ingestion.key
              optional: true
        volumeMounts:
        - name: newrelic-ini
          mountPath: /etc/config
      volumes:
      - name: newrelic-ini
        configMap:
          name: newrelic-ini
---
apiVersion: v1
kind: Service
metadata:
  name: core-banking-sim
spec:
  type: ClusterIP
  selector:
    app: core-banking-sim
  ports:
  - name: http
    port: 8000
