# for testing only
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-linux-deployment
  labels:
    app: minimal-linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal-linux
  template:
    metadata:
      labels:
        app: minimal-linux
    spec:
      containers:
        - name: minimal-linux-container
          image: alpine:latest
          command:
            [
              "/bin/sh",
              "-c",
              "apk add --no-cache curl bash redis postgresql15-client && sleep infinity",
            ]
          env:
            - name: PGPASSFILE
              value: /secrets/.pgpass
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          volumeMounts:
            - name: test-postgres-app
              mountPath: /secrets/.pgpass
              subPath: pgpass
              readOnly: true
      volumes:
        - name: test-postgres-app
          secret:
            secretName: test-postgres-app
