apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  storage:
    size: 5Gi
  superuserSecret:
    name: test-postgres
  enableSuperuserAccess: true
---
apiVersion: v1
kind: Secret
metadata:
  name: test-postgres
type: Opaque
stringData:
  username: postgres
  password: "P@ssw0rd!"
