apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: testfunc
spec:
  template:
    spec:
      containers:
        - name: tfunc
          image: ghcr.io/sloppycoder/testfunc:main-20250707-192401-9bf6ef7 # {"$imagepolicy": "test:tfunc-main"}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: db-secret
              mountPath: /secrets/database_url
              subPath: uri
              readOnly: true
      imagePullSecrets:
        - name: ghcr-cred
      volumes:
        - name: db-secret
          secret:
            secretName: test-postgres-app
