apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: testfunc
spec:
  template:
    spec:
      containers:
        - name: tfunc
          image: ghcr.io/sloppycoder/testfunc:main-20250707-214153-accfe29 # {"$imagepolicy": "test:testfunc-main"}
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_SVC
              value: redis-standalone
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: test-postgres-app
                  key: uri
      imagePullSecrets:
        - name: ghcr-cred
