apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tfunc
spec:
  template:
    spec:
      containers:
        - name: tfunc
          image: ghcr.io/sloppycoder/tfunc:main-20250707-021531-5c333b5 # {"$imagepolicy": "test:tfunc-main"}
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: db-secret
              mountPath: /secrets/database_url
              subPath: uri
              readOnly: true
      imagePullSecrets:
        - name: ghcr-cred
      volumes:
        - name: db-secret
          secret:
            secretName: test-postgres-app
