# test application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfunc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfunc
  template:
    metadata:
      labels:
        app: tfunc
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: tfunc
          image: ghcr.io/sloppycoder/tfunc:main-20250706-214214-bf4579a # {"$imagepolicy": "test:tfunc-main"}
          command: ["/bin/sleep", "infinity"]
          volumeMounts:
            - name: db-secret
              mountPath: /secrets/database_url
              subPath: uri
              readOnly: true
      volumes:
        - name: db-secret
          secret:
            secretName: test-postgres-app
            optional: true
