apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: core-banking-sim
spec:
  image: ghcr.io/vino9org/core-banking-sim
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: core-banking-sim-j
spec:
  image: ghcr.io/vino9org/core-banking-sim-j
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: fund-transfer
spec:
  image: ghcr.io/vino9org/fund-transfer
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: core-banking-sim-develop
spec:
  imageRepositoryRef:
    name: core-banking-sim
  filterTags:
    pattern: '^develop-(?P<suffix>\d{8}\-\d{6}-[0-9a-f]{7})'
    extract: '$suffix'
  policy:
    alphabetical:
      order: asc

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: core-banking-sim-j-develop
spec:
  imageRepositoryRef:
    name: core-banking-sim-j
  filterTags:
    pattern: '^develop-(?P<suffix>\d{8}\-\d{6}-[0-9a-f]{7})'
    extract: '$suffix'
  policy:
    alphabetical:
      order: asc


---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: fund-transfer-snapshot
spec:
  imageRepositoryRef:
    name: fund-transfer
  policy:
    semver:
      range: 1.1.x-snapshot
