kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base
- ingress.yaml
- image-policy.yaml

namespace: vino-dev

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: newrelic-ini
  files:
  - newrelic.ini
- name: redis-config
  files:
  - redis.conf


