kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base
- ingress.yaml

namespace: vinobank

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: newrelic-ini
  files:
  - newrelic.ini
- name: redis-config
  files:
  - redis.conf

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: fund-transfer
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/0
      value: { "name": "QUARKUS_STORK_K8S_NAMESPACE", "value": "vinobank" }

